### ISSUE TITLE
User Journey: As a user I want to take timestamped notes on a video of my choosing

### ISSUE THREAD

**Issue by m4v15** [facn2/vidNotes#1]
- [ ] I want to import videos from youtube with a share link (url) and watch them directly in the application. #12 

- [ ] I want to add topic tags to videos (future referencing). #11 

- [ ] I want to be able to click a button which allows me to leave a note at a specific time of the video. This will be treated as an editable time stamp. #4 

- [ ] I want to add  tags to notes for future referencing and filtering. #7 

- [ ] After leaving a note, I want to be able to see them alongside the video. #8 

- [ ] I would like to be able to delete & edit notes after creating them. #10
