### ISSUE TITLE
User Journey: As a user I want to be able to log in to save a view my notes

### ISSUE THREAD

**Issue by m4v15** [facn2/vidNotes#2]
- [ ] I want to be able to register #3 

- [ ] I want to be able to login with a username and password #6 

- [ ] I want to be able to login with google or github  #9 

- [ ] When logging in I want to land on a page which allows me to view all videos or notes. #13 

- [ ] I want to save notes I've made #14 

- [ ] I want to filter videos and notes by tags #15
