### ISSUE TITLE
Basic Setup

### ISSUE THREAD

**Issue by m4v15** [facn2/vidNotes#5]
- [x] design some wireframes/prototypes, and app flow #16 
  - [x] Add to readme #16 
- [x] Skeleton file structure
- [ ] Configure linter
- [x] Set up express server
- [x] set up database
  - [x] decide on schema
- [x] Set up React/redux  
  - [x] research React/redux
  - [x] webpack/babel?
- [x] Set up test folder structure
- [ ] Configure Travis CI
- [x] Initialise on Heroku
